export const RegisterItems = [
	{
		id: 1,
		name: "Username",
		type: "text",
		placeholder: "Type your username",
		className: "Form-List",
		classInputName: "Form-Input",
		minLength: 6,
		icon: "person-outline",
	},
	{
		id: 2,
		name: "Email",
		type: "email",
		placeholder: "Type your email",
		className: "Form-List",
		classInputName: "Form-Input",
		minLength: "",
		icon: "mail-outline",
	},
	{
		id: 3,
		name: "Password",
		type: "",
		placeholder: "Type your password",
		className: "Form-List",
		classInputName: "Form-Input",
		minLength: 8,
		icon: "lock-closed-outline",
	},
	{
		id: 4,
		name: "Confirm Password",
		type: "",
		placeholder: "Type your password",
		className: "Form-List",
		classInputName: "Form-Input",
		minLength: 8,
		icon: "lock-closed-outline",
	},
];
