export const ProcessDistanceItems = [
    {
        id: 1,
        name: 'User info',
        description: '',
        url: '/UseInfo',
        className: 'Process-HeaderItem',
        thumbnail: '/image/process/user-info-process.jpg',
    },
    {
        id: 2,
        name: '',
        description: '',
        url: '',
        className: 'Process-HeaderItem',
        thumbnail: '/image/process/right-arrow.jpg',
    },
    {
        id: 3,
        name: 'Vehicle info',
        description: '',
        url: '/VehicleInfo',
        className: 'Process-HeaderItem',
        thumbnail: '/image/process/vehicle-info-process.jpg',
    },
    {
        id: 4,
        name: '',
        description: '',
        url: '',
        className: 'Process-HeaderItem',
        thumbnail: '/image/process/right-arrow.jpg',
    },
    {
        id: 5,
        name: 'Success',
        description: '',
        url: '',
        className: 'Process-HeaderItem',
        thumbnail: '/image/process/success-process.jpg',
    },
]


export const UserInfoItems = [
    {
        id: 1,
        title: 'First Name',
        name: 'firstName',
        type: 'text',
        placeholder: 'Type your first name here',
        className: 'ProcessInfo-Input',
        description: '',
    },
    {
        id: 2,
        title: 'Last Name',
        name: 'lastName',
        type: 'text',
        placeholder: 'Type your last name here',
        className: 'ProcessInfo-Input',
        description: '',
    },
    {
        id: 3,
        title: 'Date of Birth',
        name: 'dateOfBirth',
        type: 'date',
        placeholder: 'Date of Birth',
        className: 'ProcessInfo-Input',
        description: '',
    }, 
    {
        id: 4,
        title: 'Email',
        name: 'email',
        type: 'email',
        placeholder: 'Type your email here',
        className: 'ProcessInfo-Input',
        description: '',
    },
    {
        id: 5,
        title: 'Phone Number',
        name: 'phoneNum',
        type: 'tel',
        placeholder: 'Phone number',
        className: 'ProcessInfo-Input',
        description: '',
    },{
        id: 6,
        title: 'Policy Number',
        name: 'policyNum',
        type: 'text',
        placeholder: 'Policy number',
        className: 'ProcessInfo-Input',
        description: '',
    },
]




export const VehicleInfoItems = [
    {
        id: 1,
        title: 'Vehicle Name',
        name: 'vehicleName',
        type: 'text',
        placeholder: 'Type your vehicle name here',
        className: 'ProcessInfo-Input',
        description: '',
    },
    {
        id: 2,
        title: 'Vehicle Modal',
        name: 'name',
        type: 'text',
        placeholder: 'Type your vehicle modal type here',
        className: 'ProcessInfo-Input',
        description: '',
    },
    {
        id: 3,
        title: 'Vehicle Version',
        name: 'vehicleVersion',
        type: 'text',
        placeholder: 'Type your vehicle version here',
        className: 'ProcessInfo-Input',
        description: '',
    }, 
    {
        id: 4,
        title: 'Vehicle Rate',
        name: 'vehicleRate',
        type: 'text',
        placeholder: 'Type your vehicle rate here',
        className: 'ProcessInfo-Input',
        description: '',
    },
    {
        id: 5,
        title: 'Vehicle Body Number',
        name: 'vehicleBodyNumber',
        type: 'tel',
        placeholder: 'Type your vehicle body number here',
        className: 'ProcessInfo-Input',
        description: '',
    },
    {
        id: 6,
        title: 'Vehicle Engine Number',
        name: 'vehicleEngineNumber',
        type: 'text',
        placeholder: 'Type your vehicle engine number here',
        className: 'ProcessInfo-Input',
        description: '',
    },
    {
        id: 7,
        title: 'Vehicle Number',
        name: 'vehicleNumber',
        type: 'text',
        placeholder: 'Type your vehicle number here',
        className: 'ProcessInfo-Input',
        description: '',
    },
]